/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    // public static void main(String[] args) {
    //     StandardCalculator calc = new StandardCalculator();
    //      calc.add(1,1);//  ;
    //     // int Result1 = calc.substract(1,1);
    //     // System.out.println(Result1);
    //     // int Result = calc.multiply(2, 2);
    //     // System.out.println(Result);
    //     // int Result2 = calc.divide(4, 2);
    //     // System.out.println(Result2);
    //     System.out.println(new App().getGreeting());
        
 public static void main(String[] args) {

    System.out.println(new App().getGreeting());

    ScientificCalculator calc = new ScientificCalculator();

    int result= calc.modulo(5, 2);

    System.out.println("modulo =" + result);

        }

    }

